### ISSUE TITLE
Add first non US language

### ISSUE THREAD

**Issue by ar-x** [ar-x/turtlecoin.lol-translations#1]
This repo will contain translations for https://turtlecoin.lol

I'll will be fleshing out the actual sentences to be translated in 2-3 days.

**Comment by ar-x** [comment]
I'll looking for someone to hash out the first non-US language real quick, mainly to aid development. Ideally the person would be experienced in writing copy in their native language (to reduce feedback, verification etc).

**Comment by SoreGums** [comment]
I'm good for English only though - site is already in English, so not sure I can help here this time.

**Comment by hurrdurrnein** [comment]
I can so German.

**Comment by ar-x** [comment]
@hurrdurrnein – We just got a submission for German, perhaps you can review it instead – https://github.com/ar-x/turtlecoin.lol-translations/pull/2. Thanks!

**Comment by hurrdurrnein** [comment]
Sure, I'd love to.

**Comment by ar-x** [comment]
👍 I'll be implementing German as the first non English. via https://github.com/ar-x/turtlecoin.lol-translations/pull/2

**Comment by mumonster** [comment]
I am ready to translate to "bahasa"

**Comment by ar-x** [comment]
@mumonster Go for it - https://github.com/ar-x/turtlecoin.lol-translations#adding-a-new-translation

**Comment by ar-x** [comment]
@adj-gh Spanish? (this is !ac)

**Comment by andreafno** [comment]
Hi! I'd like to contribute this amazing project so I translated repo for Italian; I asked in discord chat and tmac25 told me I can attach here the files (I never used github).

Have a nice day!!
[italian_turtlecoin.zip](https://github.com/ar-x/turtlecoin.lol-translations/files/2020527/italian_turtlecoin.zip)

**Comment by ar-x** [comment]
@andreafno This is super. I've imported your files here – https://github.com/ar-x/turtlecoin.lol-translations/pull/4. The next step is to ask some in our community to review it, and then we can ship it.

**Comment by andreafno** [comment]
@ar-x Great! If you have something else to translate, I'm available.

**Comment by mumonster** [comment]
https://github.com/mumonster/turtlecoin.lol-translations/tree/master/bahasa

**Comment by ar-x** [comment]
@mumonster Can you create a pull request for that. Step (5) and (6) here:

https://github.com/ar-x/turtlecoin.lol-translations/#adding-a-new-translation

**Comment by ar-x** [comment]
@andreafno What languages do you want to work with?

**Comment by andreafno** [comment]
@ar-x I can only translate English to Italian

**Comment by ar-x** [comment]
@andreafno I've opened a pull request for you here: https://github.com/ar-x/turtlecoin.lol-translations/pull/4. The next step is to find someone from the community to review it, and then we'll ship it. Thanks!

**Comment by andreafno** [comment]
@ar-x  Ok, thank you!

**Comment by mrrovot** [comment]
I submitted the spanish translation 
https://github.com/ar-x/turtlecoin.lol-translations/pull/5

**Comment by andreafno** [comment]
@ar-x A review (only by comments) is present in Italian translation, how can I confirm some changes? The "pencil" icon is greyed, I read I need "push access" to make changes.
